### PR TITLE
elasticsearch indexing utils and deserialization function

### PR DESCRIPTION
**Pull request by agarwalarjun123**
- Contains Elasticsearch indexing function
- De serialization implementation

### CODE REVIEW

**Review by darshkpatel — APPROVED** [review]
Glanced through it, Good Work
@invinciblycool  thoughts ?

**Review by darshkpatel — CHANGES_REQUESTED** [review]
@agarwalarjun123 need to change to github.com/darshkpatel/NetNetra I believe

**Comment by agarwalarjun123** [comment]
Changed it @darshkpatel  but the build is not successful as the dependencies are not there in the upstream branch

**Review by darshkpatel — APPROVED** [review]
Looks fine to me , let's wait for @invinciblycool to have a look too

**Comment by agarwalarjun123** [comment]
Should we merge it @darshkpatel  since @invinciblycool has not reviewed it.

**Comment by darshkpatel** [comment]
Yeah

**Pull request merged**
